### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by sungam3r** [ApiApprover/ApiApprover#100]
I found that due to a failed test, the CI script continued to execute. Script for ubuntu behaves normally (build failed): https://github.com/ApiApprover/ApiApprover/runs/276269521

**Comment by danielmarbach** [comment]
Added a failing test and fixed it

![image](https://user-images.githubusercontent.com/174258/67671787-dfefc280-f976-11e9-9b6b-773371428521.png)

No force pushing the removal of the failing test to make the PR green again
