### ISSUE TITLE
Invalid syntax due to missing type parameter in constructed generic parameter constraints 

### ISSUE THREAD

**Issue by jnm2** [ApiApprover/ApiApprover#103]
There is a bug in 10.0.0-beta.2 (starting in 9.2.0; 9.1.0 is fine) where `where T : System.IComparable<>` is added instead of  `where T : System.IComparable<T>`:

![image](https://user-images.githubusercontent.com/8040367/68059160-c8e00600-fcd1-11e9-9d32-22c27bcabc64.png)

It looks like this was worked on at one point: https://github.com/ApiApprover/ApiApprover/issues/67

**Comment by jnm2** [comment]
Oops, silly me! I was reading the diff backwards. 9.2.0 _fixed_ it. I'm sorry!

**Comment by sungam3r** [comment]
I confused a couple of times too.
