### ISSUE TITLE
Removing empty attribute parentheses and Attribute suffix if present

### ISSUE THREAD

**Issue by jnm2** [ApiApprover/ApiApprover#105]
Folks usually leave out the parentheses when there are no positional or named arguments:

```diff
-[Shouldly.ShouldlyMethodsAttribute()]
+[Shouldly.ShouldlyMethodsAttribute]
```

It's not common to see Attribute spelled out either and to me it feels noisy:

```diff
-[Shouldly.ShouldlyMethodsAttribute]
+[Shouldly.ShouldlyMethods]
```

What do you think?

**Comment by danielmarbach** [comment]
On the fence about cosmetics because it can open a can of worm until we argue about preferred placing of braces. I see low value but I'm willing to hear your arguments

**Comment by sungam3r** [comment]
Readability?

**Comment by jnm2** [comment]
Readability is the only thing for me. I agree that it's a small thing. Every little bit does help when attributes are placed on parameters though.

**Comment by danielmarbach** [comment]
Remove the parens for now

https://github.com/ApiApprover/ApiApprover/pull/118 in a PR
