### ISSUE TITLE
Private protected methods are not API

### ISSUE THREAD

**Issue by jnm2** [ApiApprover/ApiApprover#109]
C# 7.2 exposed the `famandassem` visibility that .NET binaries have always supported: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected

(`protected internal` compiles to `famorassem`.)

For:

```cs
public class ClassWithPrivateProtectedMethod
{
    private protected void DoSomething()
    {
    }
}
```

ApiApprover generates:

```cs
namespace PublicApiGeneratorTests.Examples
{
    public class ClassWithPrivateProtectedMethod
    {
        public ClassWithPrivateProtectedMethod() { }
        void DoSomething() { }
    }
}
```

But `DoSomething` should not be visible.

PR incoming.

**Comment by jnm2** [comment]
While adding tests, I found that nested protected internal classes are not included in the API.

**Comment by sungam3r** [comment]
Excellent! But we still cannot enable the 4 skipped tests?

**Comment by jnm2** [comment]
> Excellent! But we still cannot enable the 4 skipped tests?

No, they still fail. The skip message on all of them says that you're up against CodeDOM limitations, and this PR doesn't do anything to fix CodeDOM.

**Comment by sungam3r** [comment]
Maybe we can apply "magic marker" approach?

**Comment by jnm2** [comment]
Probably.
