### ISSUE TITLE
C#-like syntax for volatile fields

### ISSUE THREAD

**Issue by jnm2** [ApiApprover/ApiApprover#116]
Nothing special is currently done, so `volatile` on a field shows up as `modreq(System.Runtime.CompilerServices.IsVolatile)` on the field type.

(Reasons that it should be highly visible either way, besides the fact that it's a modreq: If you access a volatile field, the compiler emits a `volatile.` prefix before the stfld/ldfld instructions. It should show up in a dramatic way in your public API if the volatility changes because it's a breaking change. It's a binary behavioral breaking change because libraries compiled against an older version of your library will not use `volatile.` when they should, and it's a compile-time break because errors begin showing up if you take a ref to a suddenly-volatile field.)

**Comment by sungam3r** [comment]
Partially handled by #115
