### ISSUE TITLE
Compiler-recognized internal attributes are public API

### ISSUE THREAD

**Issue by jnm2** [ApiApprover/ApiApprover#117]
Internal (and even private) attributes are just as visible outside the assembly as inside. I disagree with https://github.com/ApiApprover/ApiApprover/issues/29: you are in reality shipping that annotation as visibly in your .NET binary as if the attribute was public. Either public and internal attributes should be equally visible or they should be equally invisible for the purposes of public API analysis.

However, no matter which way you go on that question, certain well-known attributes affect the compiler behavior regardless of their visibility. They must always be shown. Internal attributes are the only safe way to communicate with the compiler when the attributes are not defined in the target framework. The compiler even generates internal attributes for you when you use C# syntax that depends on these attributes.

The critical ones so that a project can evaluate its nullability API:

https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.allownullattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.disallownullattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnifattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.maybenullattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.maybenullwhenattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.notnullattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.notnullifnotnullattribute
https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.notnullwhenattribute
➡ Others in `System.Diagnostics.CodeAnalysis` over time

Other attributes that affect compiler or runtime behavior which aren't in all target frameworks and which should be displayed as attributes (e.g. not TupleElementNamesAttribute):

https://docs.microsoft.com/dotnet/api/system.serializableattribute
https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.callerargumentexpressionattribute
https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.callerlinenumberattribute
https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.callerfilepathattribute
https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.callermembernameattribute
https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.referenceassemblyattribute
➡ Others in `System.Runtime.CompilerServices` over time

**Comment by jnm2** [comment]
What would your preferred approach be:

1. Show all attributes regardless of visibility (my "purist" approach)
2. Add a list of full type names for attributes that must never be hidden
3. Same as 2, but also make handling of attributes configurable. Maybe instead of `bool shouldIncludeAssemblyAttributes`, an enum/class/struct `AttributeOptions`, or something like that?

**Comment by jnm2** [comment]
To make the options easily evolvable in future versions, you could add an overload:

```diff
namespace PublicApiGenerator
{
    public static class ApiGenerator
    {
        public static string GeneratePublicApi(
            Assembly assembly,
            Type[] includeTypes = null,
            bool shouldIncludeAssemblyAttributes = true,
            string[] whitelistedNamespacePrefixes = null,
            string[] excludeAttributes = null);
            
+       public static string GeneratePublicApi(
+           Assembly assembly,
+           ApiGeneratorOptions options = null);
    }
    
+   public sealed class ApiGeneratorOptions
+   {
+       public ApiGeneratorOptions();
 
+       public IReadOnlyCollection<string> ExcludeAttributes { get; set; }
 
+       public bool IncludeAssemblyAttributes { get; set; }

+       public AttributeVisibilityFilter AttributeVisibilityFilter { get; set; }
 
+       public IReadOnlyCollection<Type> IncludeTypes { get; set; }
 
+       public IReadOnlyCollection<string> WhitelistedNamespacePrefixes { get; set; }
+   }

+   public enum AttributeVisibilityFilter
+   {
+       AllAttributes,
+       OnlyWellKnownCompilerAttributes,

+       /// <summary>
+       /// Not recommended. Non-public attributes in .NET Binaries are no less visible in
+       /// reality than public attributes.
+       /// </summary>
+       OnlyPublicAndWellKnownCompilerAttributes
+   }
}
```

**Comment by danielmarbach** [comment]
We already have         static readonly HashSet<string> SkipAttributeNames = new HashSet<string>I'd say we stick to that approach because it follows a pattern that is known to users of this libs. Users can always whitelist again if needed

**Comment by jnm2** [comment]
@danielmarbach Just making sure I understand, that sounds like option 2 above. Does that sound right to you?

**Comment by jnm2** [comment]
I got https://github.com/ApiApprover/ApiApprover/pull/119 ready just in case.
