### ISSUE TITLE
10.0.0 changes make it impossible to call GeneratePublicApi with just an assembly argument

### ISSUE THREAD

**Issue by adamralph** [ApiApprover/ApiApprover#139]
```c#
ApiGenerator.GeneratePublicApi(typeof(Foo).Assembly));
```

> The call is ambiguous between the following methods or properties: 'ApiGenerator.GeneratePublicApi(Assembly, ApiGeneratorOptions?)' and 'ApiGenerator.GeneratePublicApi(Assembly, Type[]?, bool, string[]?, string[]?)'

This worked in 9.x.

**Comment by danielmarbach** [comment]
doesn't

```
typeof(Foo).Assembly.GeneratePublicApi();
```

work for you?

**Comment by adamralph** [comment]
No, calling it using extension method syntax makes no difference. The problem is that there are two overloads, each with a first parameter of type `Assembly`, and both have the second paramater as optional. Effectively, that means there is no such thing as an optional second parameter in the API, because one of the two optional second parameteres _must_ have an argument provided. In order to have a truly optional second parameter, one of the two overloads must have the parameter as mandatory, so that a call without a second parameter is resolved to the single overload that has an optional parameter.

**Comment by adamralph** [comment]
OK, scratch that previous comment. I didn't realise that only _one_ of the overloads is in extension method, so it does work when calling `typeof(Foo).Assembly.GeneratePublicApi()` (although your linked example is suppling an argument for the second parameter).

But still, it feels weird to have on overload as an extension method and the other not. If you make the second param mandatory in one of them, they can both be extension methods and have the same level of discoverability.

**Comment by danielmarbach** [comment]
Happy to accept a PR to improve this situation if you have time to give it a stab

**Comment by adamralph** [comment]
Sure, here you go: https://github.com/ApiApprover/ApiApprover/pull/141

**Comment by danielmarbach** [comment]
Closing this as the PR was also closed
