### ISSUE TITLE
10.0.0-beta5 has incorrect type modifier order

### ISSUE THREAD

**Issue by adamralph** [ApiApprover/ApiApprover#140]
## 9.x

`static class`

## 10.0.0-beta5

`class static`

**Comment by danielmarbach** [comment]
9.x currently does `class static` and 10.x switches it to `static class`, see https://github.com/Particular/NServiceBus/pull/5477/files#diff-d4a1cafe3482cd781cba4e76c17889dcL28-R28

Do you have a repro or a sample I can check out?

**Comment by adamralph** [comment]
You're correct. I had it the wrong way round. 🤦‍♂

**Comment by sungam3r** [comment]
Relates to shouldly/shouldly#592

**Comment by danielmarbach** [comment]
Do you want to give beta 8 a stab? There is a known issue with a bit too much whitespace with the new modifer that I already sent a PR for. Other than that I hope this is it for 10.0.0
