### ISSUE TITLE
Order of keywords

### ISSUE THREAD

**Issue by gpetrou** [ApiApprover/ApiApprover#80]
We have the following class:

    public static class Utilities

However, the generated API is:

    public class static Utilities

Would it be possible to fix the order of keywords?

**Comment by sungam3r** [comment]
Keywords are sorted alphabetically. The initial order should not be supported, otherwise the public api changed, which should not be due to the modifiers only order.

**Comment by danielmarbach** [comment]
Thanks @sungam3r for chiming in. You rock! The only thing left to say is: What ivan said (I need to make this a meme ;) ) and close the issue

**Comment by jnm2** [comment]
So long as it is a stable sort, there is no reason to sort it alphabetically. The order should follow standard .NET style. `class`/`struct`/`enum`/etc should unconditionally be last.

**Comment by jnm2** [comment]
Would you accept a PR to fix this for v10?

**Comment by sungam3r** [comment]
@jnm2 In principle, I agree. My original answer was against the order of the modifiers being **exactly the same** as the original order.

> class/struct/enum/etc should unconditionally be last

This is what is happening now.

**Comment by jnm2** [comment]
> This is what is happening now.

In versions 8, 9, and 10 beta, it's doing `public class static`. `class` is not last.

**Comment by sungam3r** [comment]
Yes, I was wrong.

**Comment by danielmarbach** [comment]
I'd be ok to take a PR if it prevents OCDs from tingling
😉

**Comment by danielmarbach** [comment]
One important note though. The goal of this tool was to have csharp like syntax of the public API. Creating output that is compliant with any syntax highlighting wasn't

**Comment by jnm2** [comment]
For test cases, ran across this:

```cs
public struct readonly AsyncLocalValueChangedArgs<T> { }
```

**Comment by sungam3r** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/a4e8cc01-e81b-4f63-8782-f8467079c2aa/static-classes-with-codedom?forum=netfxbcl
https://stackoverflow.com/questions/6308310/creating-extension-method-using-codedom

**Comment by sungam3r** [comment]
Just like an idea. We can insert magic word instead of `static` and then (after rendering into text) replace it with normal one:

```
public class static_12345_ololo_ku_pa_bin_ga_bon_go A { }
```
->
```
public static class A { }
```

```c#
resultText = resultText.Replace("class static_12345_ololo_ku_pa_bin_ga_bon_go", "static class")
```

This nullifies the possibility of misapplying a regular expression.
