### ISSUE TITLE
Including ApiGenerator.cs in projects with <Nullable>enable</Nullable> causes unsuppressible warnings

### ISSUE THREAD

**Issue by jnm2** [ApiApprover/ApiApprover#97]
The PublicApiGenerator package includes a file as source which results in warnings when included in any project with `<Nullable>enable</Nullable>`:

![image](https://user-images.githubusercontent.com/8040367/67165548-5e83a900-f354-11e9-8c27-901458e87689.png)

GlobalSuppressions.cs is not an option because the warnings are coming from the C# compiler itself. The only recourse is to add pragmas to the source file itself to silence a CS8600, CS8603, and CS8625 (so far). Changes to the source file itself can only be done by the package publisher.

**Comment by danielmarbach** [comment]
9.x no longer ships sources. I'm guessing there is nothing to fix then?

**Comment by jnm2** [comment]
You're right, that's awesome. Thank you!
